myapp/urls.py
from django.urls import path
from .import views

app_name = 'myapp'

urlpatterns = [
    path('index/', views.index , name='index'),
    path('create/', views.create , name='create'),
    path('update/<pk>', views.update , name='update'),
    path('delete/<pk>', views.delete, name='delete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf.urls.static import static
from .import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include("myapp.urls")),
    path("", views.index)
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

class Book(models.Model):
    name = models.CharField(max_length=100)
    book_pdf = models.FileField(upload_to='pdfs/', null=True, blank=True)
    book_cover = models.ImageField(upload_to='bookcovers/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name
# Create your models here.

myapp/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name','book_pdf','book_cover')

myapp/views.py
from django.shortcuts import get_object_or_404,render, redirect
from django.urls import reverse
from .models import Book
from .forms import BookForm


def index(req):
    books = Book.objects.all()
    return render(req, "myapp/index.html",{'books':books})

def create(req):
    if req.method == "POST":
        form = BookForm(req.POST, req.FILES)
        if form.is_valid():
            books = form.save(commit=False)
            books.save()
            return redirect('myapp:index')
    else:
        form = BookForm()
    return render(req, 'myapp/create.html', {'form': form})

def update(req,pk):
    books = get_object_or_404(Book, pk=pk)
    if req.method == 'POST':
        form = BookForm(req.POST, req.FILES, instance=books)
        if form.is_valid():
            books = form.save(commit=False)
            books.save()
            return redirect('myapp:index')
    else:
        form = BookForm(instance=books)
    return render(req, 'myapp/update.html', {'form':form})

def delete(req,pk):
    books = Book.objects.get(pk=pk)
    books.delete()
    return redirect("myapp:index")

templates/base.html
<!doctype html>
<html lang="en">
{% include 'head.html' %}
{% include 'header.html' %}
    <body style="background-color: black;">
    {% block con %}

    {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>
</html>

templates/head.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NewHoony</title>
    {% load static %}
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

templates/header.html
<header>
    <nav class="navbar">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="color: rgb(0, 0, 0);">
            <img src="/static/assets/music.png" width="30" height="30" class="d-inline-block align-text-top">
            <b>NewHoon's Note</b>
          </a>
        </div>
    </nav>
</header>

templates/myapp/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block con %}
<style>
    input[type="text"], input[type="file"], input[type="textarea"] {
    width: 500px;
  }
  </style>

<div class="container" style="padding-top: 300px; color: white;">
    <h1>Upload Page</h1>
    <a href ="{% url 'myapp:index' %}"><button class="btn btn-outline-light" style="padding-bottom: 10px; float: right;">뒤로가기</button></a>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <hr>
        <button type="submit" class="btn btn-outline-light">Upload</button>
    </form>
</div>

{% endblock %}

templates/myapp/index.html
{% extends 'base.html' %}
{% block con %}
    <div class ="container" style="padding-top: 300px; padding-bottom: 10px; color: white;">
        <div class="text-center">
            <h1>Music Sheet</h1>
            <a href="{% url 'myapp:create' %}"><button class="btn btn-outline-light" style="float: right;">ADD</button></a>
        </div>
        <div class="container" style="display: flex;">
            <div class="col-12">
                <div style="color: white;">
                    <div class="card-grid">
                        {% for book in books %}
                            <div class="card" style="width: 250px; height: auto; background-color: black;">
                                <div class="card-body">
                                    {% if book.book_cover %}
                                        <img src="{{ book.book_cover.url }}" class="card-img-top" alt="{{ book.name }}" width="100%" height="100%">
                                    {% else %}
                                        <span class="text-muted">No cover</span>
                                    {% endif %}
                                    <div class="card-text" style="height: auto; margin: 0.5rem 0;">
                                        {{ book.name }}
                                        <div style="display: flex;">
                                            <a href="{{ book.book_pdf.url }}" class="btn btn-outline-light btn-sm" target="_blank">PDF</a>
                                            <a href="{% url 'myapp:update' book.pk %}"><button class="btn btn-outline-light btn-sm"  style="margin:0 0.3rem">Mod</button></a>
                                            <form method="post" action="{% url 'myapp:delete' book.pk %}">
                                                {% csrf_token %} 
                                                <button type="submit" class="btn btn-outline-danger btn-sm" style="margin-left: 4.5rem;">DEL</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

templates/myapp/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block con %}
<style>
  input[type="text"],input[type="file"]  {
  width: 500px;
  margin: 0 auto;
}
</style>
<div class="text-center" style="height: 100%; margin-top: 1rem;">
  <h1>Edit Household Account</h1>
  <form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-outline-primary">Save Changes</button>
  </form>
</div>
{% endblock %}